name: OCaml CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0
      
      - name: Install dune
        run: opam install dune

      - name: Install dependencies
        run: |
          eval $(opam env)
          opam update
          opam install . --deps-only --with-test

      - name: Build
        run: |
          eval $(opam env)
          dune build

      # - name: Run tests
      #   run: dune runtest

      - name: Check formatting
        run: |
          eval $(opam env)
          opam install ocamlformat
          dune build @fmt || {
            echo '❌ Formatting issues found. Run `dune build @fmt --auto-promote` to fix.';
            exit 1;
          }
